# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fcb223190c205fdc967a8a77a3d0aca2454ea669f511637368c052befb2c55f54684f334ae08d65af6cc09e7f3a5a36f27eb0533a5cbf448b6fa4e533163cfb

test:
  secret_key_base: 7b73dbb19bcfa152ebaea9559fd2df52d419090456802da1977e609fcb4e662873f3250742492e044f510022687c2e76695ea4971f123502491e35c897651f2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
